config/routes.rb
# frozen_string_literal: true

require 'resque/server'

Rails.application.routes.draw do
  mount API::Base => '/'
  mount GrapeSwaggerRails::Engine, at: '/documentation'

  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # например localhost/ru/questions, localhost/en/questions, localhost/questions
  # locale: /#{I18n.available_locales.join("|")}/ - проверка, что запрошенная локаль входит
  # в массив %i[en ru], а ("|") - "или" (локаль или такая, или такая.....)
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users, skip: :omniauth_callbacks

    authenticate :user do
      mount Resque::Server.new, at: '/jobs'
    end

    root 'events#index'

    resources :events do
      # вложенный ресурс комментовX
      resources :comments, only: %i[create destroy]
      resources :photos, only: %i[create destroy]
      resources :subscriptions, only: %i[create destroy]

      post :show, on: :member
    end

    resources :users, only: %i[show edit update]
  end
end

# Если у события есть пин-код, то при обращении к "events#show" в запросе будет
# рендериться форма ввода пинкода. В эту форму юзер вводит пинкод, нажимает отправить
# и при отправке эта же форма будет выдавать post-запрос по адресу этого же события,
# а именнно "events#show" (это GET-зпрос). Добавляем двойной функционал приема POST-
# запроса по этому же url.

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: %i[google_oauth2 vkontakte github]
  # Юзер может создавать много событий

  # У юзера должно быть имя не длиннее 35 букв
  validates :name, presence: true, length: { maximum: 15 }, allow_blank: true

  # Юзер может создавать много событий и комментариев
  has_many :events, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :identities, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :photos, dependent: :destroy

  # без обращения к DNS-почтовым серверам для проверки существования доменного
  # проверяем корректность вводимых емэйлов
  validates :email, presence: true, uniqueness: true, 'valid_email_2/email': true

  # При создании нового юзера (create), перед валидацией объекта выполнить
  # метод set_name (потому что devise ни знает ничего о поле "name", которое
  # у нас presence: true)
  before_validation :set_name, on: :create

  validate :password_complexity

  before_save :ensure_authentication_token
  # Если юзер уже подписывался, но хочет залогиниться, пройдя все валидации
  after_commit :link_subscriptions, on: :create

  mount_uploader :avatar, AvatarUploader

  def ensure_authentication_token
    self.authentication_token ||= generate_authentication_token
  end

  class << self
    def find_for_oauth(provider, access_token)
      find_or_create_user(access_token, provider)
    end

    private

    def find_or_create_user(access_token, provider)
      email = access_token.info.email
      return if email.blank?

      name =
        case provider
        when :github then access_token.info.nickname
        else access_token.info.first_name
        end

      avatarka =
        case provider
        when :vkontakte then access_token.extra.raw_info.photo
        else access_token.info.image
        end

      user = find_by(email:) || create_oauth_user(access_token, name, avatarka)

      provider = access_token.provider
      uid = access_token.uid

      Identity.find_or_create_by(provider:, uid:, user:).user
    end

    def create_oauth_user(access_token, name, avatarka)
      create(
        name: name.first(14),
        email: access_token.info.email,
        password: "#{Devise.friendly_token.first(16)}!".chars.shuffle.join,
        avatar: avatarka
      )
    end
  end

  # Переопределенный метод одного из родительских классов Devise
  # Отличается от родителького только тем, что использует .deliver_later
  # что кладет отправку почты в очередь фоновых задач
  # https://stackoverflow.com/questions/27518070/active-job-with-rails-4-and-devise
  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end

  private

  # Задаем юзеру случайное имя, если оно пустое
  def set_name
    self.name = "stranger №#{rand(777)}" if name.blank?
  end

  # проверка для сложности пароля
  def password_complexity
    # Regexp extracted from https://stackoverflow.com/questions/19605150/regex-for-password-must-contain-at-least-eight-characters-at-least-one-number-a
    return if password.blank? || password =~ /(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-])/

    errors.add(:password, :password_error)
  end

  # Если подписчик вдруг захотел залогиниться
  def link_subscriptions
    Subscription.where(user_id: nil, user_email: email)
                .update_all(user_id: id)
  end

  def generate_authentication_token
    loop do
      token = Devise.friendly_token
      break token unless User.where(authentication_token: token).first
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def vkontakte
      authenticate_user(:vkontakte)
    end

    def github
      authenticate_user(:github)
    end

    def google_oauth2
      authenticate_user(:google)
    end

    private

    def authenticate_user(provider)
      @user = User.find_for_oauth(provider, request.env['omniauth.auth'])

      if @user.nil?
        flash[:alert] =
          t('devise.omniauth_callbacks.failure', kind: provider, reason: t('devise.omniauth_callbacks.email_missing'))

        redirect_to new_user_session_path
      elsif @user.persisted?
        flash[:notice] = t('devise.omniauth_callbacks.success', kind: provider)

        sign_in_and_redirect @user, event: :authentication
      else
        flash[:alert] =
          t('devise.omniauth_callbacks.failure', kind: provider,
                                                 reason: t('devise.omniauth_callbacks.authentication_error'))

        redirect_to root_path
      end
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# Контроллер, управляющий пользователями
class UsersController < ApplicationController
  # Встроенный в девайз фильтр — посылает незалогиненного пользователя
  before_action :authenticate_user!, except: [:show]
  before_action :set_user!, except: [:edit]

  # Задаем объект @user (текущий юзер) для шаблонов и экшенов
  before_action :set_current_user, except: [:show]

  before_action :authorize_user!, except: [:show]
  after_action :verify_authorized, except: [:show]

  def show; end

  def edit
    @providers = User.find(params[:id]).identities.map(&:provider)
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: t('controllers.users.updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def set_user!
    if params[:id] == 'sign_out'
      sign_out current_user
      redirect_to root_path
    else
      @user = User.find params[:id]
    end
  end

  def set_current_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:name, :email, :avatar)
  end

  def authorize_user!
    authorize(@user || User)
  end
end

app/views/users/_form.html.erb
<%# html: {multipart: true} - для случая загрузок аватарок %>
<%= form_for @user, html: {multipart: true} do |f| %>
  <%= render partial: 'partials/form_errors', locals: {model: @user} %>

  <div class="form-group mb-2">
    <%= f.label :name, class: 'form-label fw-bold' %>
    <%= f.text_field :name, class: 'form-control shadow-sm' %>
  </div>

  <div class="form-group mb-2">
    <%= f.label :email, class: 'form-label fw-bold' %>
    <%= f.text_field :email, class: 'form-control shadow-sm' %>
  </div>

  <div class="form-group">
    <%= f.label :avatar, t('text.load_avatar') %>
    <p><%= image_tag(@user.avatar.thumb.url) if @user.avatar? %></p>
    <%= f.file_field :avatar %>
  </div>

  <div class="col-md-7 mb-3">
    <%= f.label :avatar, t('text.load_avatar'), class: 'btn btn-sm btn-secondary active' %>
    <%= f.file_field :avatar, class: 'visually-hidden' %>
  </div>

  <div class="form-group mb-2">
    <%= link_to t('buttons.back'), :back, class: 'link-secondary active'%>
    <%= t('text.or')%>
    <%= f.submit t('buttons.save'), class: 'btn btn-primary rounded-pill' %>
  </div>
<% end %>

app/views/users/_user.html.erb
<span class="user">
  <span class="user-avatar">
    <%= image_tag(user_avatar(user), class: 'img-icon', style: 'height: 28px;') %>
  </span>
  <span class="user-name fs-5">
	<%# request.path - путь текущего запроса %>
    <% if request.path == user_path(user) %>
      <%= user.name %>
    <% else %>
      <%= link_to user.name, user_path(user), class: 'link-dark'%>
    <% end %>
  </span>
</span>

app/views/users/edit.html.erb
<% provide :page_title, t('other.profile_editing') %>

<%= content_tag(:h1, t('titles.account_edit'), class: 'text-left fw-light') %>

<div class="row">
  <div class="col-md-6 buffer-top">
    <%= render 'form' %>

      <%# Ссылка на смену пароля текущего залогиненного юзера (этот путь %>
      <%# генерит девайз) %>
      <%= content_tag(:p, link_to(t('buttons.password_edit'),
      edit_user_registration_path), class: 'buffer-top') %>
  </div>
</div>

app/views/users/show.html.erb
<% provide :page_title, t('other.profile', name: @user.name) %>

<div class="text-center">
  <%= content_tag(:h1, @user.name) %>

  <%= image_tag user_avatar(@user), class: 'avatar' %>

  <% if @user == current_user %>
    <%= content_tag(
          :p, link_to(t('titles.account_edit'), edit_user_path(@user),
          class: 'btn btn-outline-primary rounded-pill fw-light'), class: 'buffer-top'
        ) %>
  <% end %>

  <div class="row">
    <div class="col-md-12">
      <% if @user.events.any? %>
        <%= content_tag(:h3, t('titles.organized'), class: 'fw-light') %>
        <div class="row mt-3">
          <%= render partial: 'events/event', collection: @user.events %>
        </div>
      <% else %>
        <%= content_tag(:p, t('text.no_events'), class: 'buffer-top') %>
      <% end %>
    </div>
  </div>
</div>