config/routes.rb
# frozen_string_literal: true

require 'resque/server'

Rails.application.routes.draw do
  mount API::Base => '/'
  mount GrapeSwaggerRails::Engine, at: '/documentation'

  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # например localhost/ru/questions, localhost/en/questions, localhost/questions
  # locale: /#{I18n.available_locales.join("|")}/ - проверка, что запрошенная локаль входит
  # в массив %i[en ru], а ("|") - "или" (локаль или такая, или такая.....)
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users, skip: :omniauth_callbacks

    authenticate :user do
      mount Resque::Server.new, at: '/jobs'
    end

    root 'events#index'

    resources :events do
      # вложенный ресурс комментовX
      resources :comments, only: %i[create destroy]
      resources :photos, only: %i[create destroy]
      resources :subscriptions, only: %i[create destroy]

      post :show, on: :member
    end

    resources :users, only: %i[show edit update]
  end
end

# Если у события есть пин-код, то при обращении к "events#show" в запросе будет
# рендериться форма ввода пинкода. В эту форму юзер вводит пинкод, нажимает отправить
# и при отправке эта же форма будет выдавать post-запрос по адресу этого же события,
# а именнно "events#show" (это GET-зпрос). Добавляем двойной функционал приема POST-
# запроса по этому же url.

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  # Событие принадлежит юзеру
  belongs_to :user

  has_one_attached :snapshot

  has_many :photos, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  # Для того, чтобы  рельсы понимали, какой класс лежит в связи
  # ':subscribers' - source: :user - это то поле в таблице subscriptions
  # на которое эта связь будет ссылаться
  has_many :subscribers, through: :subscriptions, source: :user

  # Заголовок должен быть, и не может быть длиннее 255 букв
  validates :title, presence: true, length: { maximum: 255 }

  # Также у события должны быть заполнены место и время проведения
  validates :address, presence: true
  validates :datetime, presence: true

  scope :randomize, -> { order('random()') }

  # Все, кто идет на событие
  def visitors
    [user, *subscribers].uniq
  end

  # совпадает ли переданный параметр с пинкодом этого события
  def pincode_valid?(pin2chek)
    pincode == pin2chek
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

# Контроллер, управляющий событиями
class EventsController < ApplicationController
  protect_from_forgery except: :show

  # Встроенный в девайз фильтр - посылает незалогиненного пользователя
  before_action :authenticate_user!, except: %i[show index]

  # Задаем объект @event для экшена show
  before_action :set_event, only: [:show]

  # Задаем объект @event от текущего юзера для других действий
  before_action :set_current_user_event, only: %i[edit update destroy]

  before_action :password_guard!, only: [:show]

  before_action :authorize_event!, except: %i[index show]
  after_action :verify_authorized, except: %i[index show]

  def index
    @events = Event.randomize
  end

  def show
    @new_comment = @event.comments.build(params[:comment])
    @new_subscription = @event.subscriptions.build(params[:subscription])
    @new_photo = @event.photos.build(params[:photo])
  end

  def new
    @event = current_user.events.build
  end

  def edit; end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      redirect_to @event, notice: t('controllers.events.created')
    else
      render :new
    end
  end

  def update
    if @event.update event_params
      redirect_to @event, notice: t('controllers.events.updated')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path, notice: t('controllers.events.destroyed')
  end

  private

  def password_guard!
    # Если у события нет пина, то нам охранять нечего
    return true if @event.pincode.blank?
    # если юзер залогинен и текущий юзер совпадает с автором события
    return true if signed_in? && current_user == @event.user

    # Юзер на чужом событии (или не за логином). Проверяем, правильно ли передал
    # пинкод. Если правильно, запоминаем в куках этого юзера этот пинкод для
    # данного события.
    remember_pin = "events_#{@event.id}_pincode".to_sym

    if params[:pincode].present? && @event.pincode_valid?(params[:pincode])

      # чтоб при следующем обращении к событию заново не вводить пин, сохраним
      # его в куках в ключе "events_#{@event.id}_pincode":
      # cookies.permanent["events_#{@event.id}_pincode".to_sym] = params[:pincode]
      cookies[remember_pin] = { value: params[:pincode], expires: 6.hours.from_now }
      cookies.encrypted.permanent[:user_id] = current_user.id if current_user.present?
    end

    # Проверяем — верный ли в куках пинкод, если нет — ругаемся и рендерим форму
    pincode = cookies.permanent[remember_pin]

    return if @event.pincode_valid?(pincode)

    cookies.delete remember_pin

    flash.now[:alert] = t('controllers.events.wrong_pincode') if params[:pincode].present?

    render 'password_form'
  end

  def set_current_user_event
    @event = current_user.events.find(params[:id])
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event)
          .permit(:title, :address, :datetime,
                  :description, :pincode, :notifications, :snapshot)
  end

  def authorize_event!
    authorize(@event || Event)
  end
end

app/views/events/_button.html.erb
<head>
  <script src="https://api-maps.yandex.ru/2.1/?apikey=<%= Rails.application.credentials.dig(:maps, :api_key) %>&lang=ru_RU" type="text/javascript"></script>
  <script>
    ymaps.ready(() => {
      const address = document.getElementById('map').getAttribute('data-address');

      const myMap = new ymaps.Map("map", {
        center: [
          55.76, 37.64
        ],
        zoom: 10
      });

      const myGeocoder = ymaps.geocode(address);

      myGeocoder.then(function (res) {
        const coordinates = res.geoObjects.get(0).geometry.getCoordinates();

        myMap.geoObjects.add(new ymaps.Placemark(coordinates, {
          iconContent: address
        }, {preset: 'islands#blueStretchyIcon'}));

        myMap.setCenter(coordinates);
        myMap.setZoom(15);
      }, function (err) {
        alert('Ошибка при определении местоположения');
      });
    });
  </script>
</head></p><button class="btn btn-warning active btn-sm fs-5" type="button" style="width: 180px; height: 35px;" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
<%= t('text.show_on_map') %></button></p><div class="collapse" id="collapseExample"><div class="card card-body">
<div class="modal-dialog modal-l">
  <div class="modal-content">
    <div class="modal-header">
      <div id="map" data-address="<%= @event.address %>" style="width: 600px; height: 350px"></div>
    </div>
  </div>
</div></div></div>

app/views/events/_event.html.erb
<div class="col-sm-6 col-md-5">
  <div class="thumbnail mb-4 shadow">

    <%= content_tag 'div', '', class: 'event-background',
      style: "background-image: url(#{event_photo(event)})" %>

    <div class="thumbnail-inner event-info-inner">
      <div class="caption m-2">
        <div class="event-description">
          <%= content_tag(:h3, link_to(event.title, event_path(event)), class: 'fw-light') %>
          <%= content_tag(:h5, l(event.datetime, format: :long), class: 'fw-lighter') %>
          <%= content_tag(:div, event.address, class: 'buffer-both text-break') %>
          <div>
            <% event.visitors.sample(2).each do |user| %>
              <%= link_to(user_avatar_thumb(user), user_path(user)) %>
            <% end %>
          </div>
          <% if event.datetime < Time.now %>
               <%= content_tag(:div, t('other.ended'), class: 'buffer-both text-break') %>
          <% else %>
               <%= content_tag(:div, t('other.expected'), class: 'buffer-both text-break') %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <%= render partial: 'partials/form_errors', locals: {model: @event} %>

  <div class="form-group mb-2">
    <%= f.label :title, class: 'fs-5' %>
    <%= f.text_field :title, class: 'form-control shadow-sm' %>
  </div>

  <div class="form-group mb-2">
    <%= f.label :address, class: 'fs-5' %>
    <%= f.text_field :address, class: 'form-control shadow-sm' %>
  </div>

  <div class="form-group mb-2">
    <%= f.label :datetime, class: 'fs-5' %>
    <p><%= f.datetime_select :datetime, class: 'form-select shadow-sm' %></p>
  </div>

  <div class="form-group mb-2">
    <%= f.label :description, class: 'fs-5' %>
    <%= f.text_area :description, class: 'form-control shadow-sm' %>
  </div>

  <div class="form-check form-switch mb-2">
    <% if @event.notifications %>
      <%= f.check_box :notifications, class: 'form-check-input shadow-sm', checked: true %>
    <% else %>
      <%= f.check_box :notifications, class: 'form-check-input shadow-sm' %>
    <% end %>
    <%= f.label t('.email_notifications'), class: 'form-check-label' %>
  </div>

  <div class="form-group col-md-4 mt-2 mb-3 ">
    <%= f.label :pincode, class: 'fs-5' %>
    <%= f.text_field :pincode, class: 'form-control shadow-sm' %>
  </div>

  <div class="form-group col-md-8 mb-4">
    <%= f.label :snapshot, t('events.add_snapshot') %>
    <%= f.file_field :snapshot, class: 'btn btn-lg btn-secondary active' %>
  </div>

  <div class="actions">
    <%= link_to t('buttons.back'), user_path(current_user), class: 'link-secondary' %>
    <%= t('text.or')%>
    <%= f.submit t('buttons.save'), class: 'btn btn-primary rounded-pill shadow-sm' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<%= content_tag(:h1, t('titles.event_edit'), class: 'text-center fw-light') %>
<%= render 'form', event: @event %>

app/views/events/index.html.erb
<% provide :page_title %>

<%= content_tag(:h2, t('titles.events_all'), class: 'fw-light fs-1 text-dark text-center my-4 border-top pt-2') %>

<div class="buffer-both">
  <%= link_to t('titles.event_create'), new_event_path, class: 'btn btn-success' %>
</div>

<div class="row buffer-bottom">
  <%# Рендерим сразу массив событий, каждый в паршиале 'events/event' %>
  <%= render partial: 'events/event', collection: @events %>
</div>

app/views/events/new.html.erb
<% provide :page_title, t('other.new_event') %>

<%= content_tag(:h1, t('titles.event_create'), class: 'text-center fw-light mb-0') %>

<div class="row">
  <%= render 'form' %>
</div>

app/views/events/password_form.html.erb
<%= content_tag(:h1, t('titles.pincode_access')) %>
<%# форма будет отправлена на тот же url, где она отобразилась %>
<%= form_tag('', method: 'post') do |f| %>
  <div class="col-md-4 mb-3">
    <%= label :pincode, t('text.pincode'), class: 'form-label' %>
    <%= text_field_tag :pincode, params[:pincode], class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= submit_tag t('buttons.send'), class: 'btn btn-primary rounded-pill' %>
  </div>
<% end %>
<%= link_to t('text.to_main'), events_path %>

app/views/events/show.html.erb
<% provide :page_title, t('other.event', event: @event.title) %>

<div class="event">
  <div class="event-info row">
    <div class="col-md-12 event-info-inner rounded">
      <%= content_tag 'div', '', class: 'event-background',
        style: "background-image: url(#{event_photo(@event)})" %>

      <div class="row event-banner">
        <div class="col-md-8 px-4 py-3">
          <div class="event-description">
            <div class="row">
              <div class="col">
                <% if @event.snapshot.attached? %>
                  <div class="carousel-item active">
                    <%= image_tag @event.snapshot.variant(resize_to_fit: [900, 900]), class: 'img-fluid img-thumbnail' %>
                  </div>
                <% end %>
              </div>
            </div>
            <%= content_tag(:h1, @event.title, class: 'text-center fw-light') %>
            <%= content_tag(:h3, l(@event.datetime, format: :long), class: 'fw-lighter') %>
            <%= content_tag(:h3, link_to(@event.address, "https://yandex.ru/maps/?text=#{@event.address}"),
                 class: 'fw-light text-info') %>
            <%= content_tag(:p, @event.description, class: 'text-break') %>
          </div>

          <%= render partial: 'events/button' %>

          <div class="form-group mb-2">
            <% if current_user_can_edit?(@event) %>
              <div class="buffer-top">
                <%= link_to t('buttons.change'), edit_event_path(@event),
                class: 'btn btn-secondary mb-1 rounded-pill' %>
                <%= link_to t('buttons.event_delete'), event_path(@event), class: 'btn btn-danger mb-1 rounded-pill',
                method: :delete, data: { confirm: t('.are_you_sure') } %>
              </div>
            <% end %>

            <div class="row">
              <%= content_tag(:h3, t('titles.event_creator'), class: 'text-center mt-4 fw-light') %>
              <div class="d-flex justify-content-center">
                <a href="<%= user_path(@event.user) %>" class="p-1 link-dark">
                  <div>
                    <%= image_tag user_avatar(@event.user), class: 'avatar-event border border-3 border-white' %>
                    <%= content_tag(:div, content_tag(:strong, @event.user.name, class: 'fs-3 text-light fw-light'), class: 'text-center mt-2') %>
                  </div>
                </a>
              </div>
            </div>

            <div class="row">
              <div class="col-md-8">
                <div class="event-photos">
                  <% unless @event.photos.count.zero? %>
                  <%= content_tag(:h3, t('titles.event_photos', count: @event.photos.count), class: 'fw-light mb-3') %>
                  <div
                    class="event-photos-gallery shadow">
                    <%# Выводим все фотографии события <!-- Carousel -->%>
                    <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
                      <div class="carousel-inner rounded">
                        <%= render partial: 'photos/photo', collection: @event.photos.except(@new_photo).shuffle %>
                      </div>
                      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                      </button>
                      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                      </button>
                    </div>
                  </div>
                <% end %>

                <div class="d-flex justify-content-center">
                  <button type="button" class="btn btn-secondary mt-3 <%= 'disabled' unless current_user.present? %>" data-bs-toggle="modal" data-bs-target="#fileLoad">
                    <%= t('.add_photo') %>
                  </button>
                </div>
                <div class="d-flex justify-content-center mt-3">
                  <% unless current_user.present? %>
                  <p class="text-danger fw-light"><%= t('.only_authorized_users') %></p>
                <% end %>
              </div>

              <!-- Modal photo download -->
              <div class="modal" id="fileLoad" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="fileLoadLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered">
                  <div class="modal-content">
                    <div class="modal-header">
                      <%= content_tag(:h5, t('.load_photo'), class: 'modal-title') %>
                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                      <div class="event-photo-form">
                        <%= render partial: 'photos/form', locals: {photo: @new_photo || @event.photos.build} %>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div class="row justify-content-md-center">
              <div class="col-md-11 my-4">
                <% if @event.comments.exists? %>
                  <%= content_tag(:h3, t('.comments', count: @event.comments.count), class: 'fw-light') %>
                  <%= render partial: 'comments/commentable', locals: {html_id: "comments"} %>
                </div>
              <% else %>
                <%= content_tag(:em, content_tag(:h6, t('.no_comments_yet'), class: 'text-center my-5 text-secondary')) %>
                <%= render partial: 'comments/form',
							locals: {comment: @new_comment || @event.comments.build} %>
              <% end %>
            </div>
          </div>

          <div class="col-md-6">
            <% if @event.subscriptions.exists? %>
              <div class="event-subscriptions mt-3">
                <%= content_tag(:h3, t('titles.event_subscribers', count: @event.subscriptions.count), class: 'mb-3') %>
                <div>
                  <div class="form-group mb-2">
                    <%= render partial: 'subscriptions/subscription',
                collection: @event.subscriptions.except(@new_subscription).shuffle %>
                  </div>
                </div>
              </div>
            <% else %>
              <%= content_tag(:em, content_tag(:p, t('.members_be_here'), class: 'text-center text-secondary my-3')) %>
            <% end %>
            <% unless @event.user == current_user || @event.subscribers.include?(current_user) %>
            <div class="buffer-both">
              <%= render partial: 'subscriptions/form', locals: {
                 subscription: @new_subscription || @event.subscriptions.build } %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div></div></div>