config/routes.rb
# frozen_string_literal: true

require 'resque/server'

Rails.application.routes.draw do
  mount API::Base => '/'
  mount GrapeSwaggerRails::Engine, at: '/documentation'

  devise_for :users, only: :omniauth_callbacks, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # например localhost/ru/questions, localhost/en/questions, localhost/questions
  # locale: /#{I18n.available_locales.join("|")}/ - проверка, что запрошенная локаль входит
  # в массив %i[en ru], а ("|") - "или" (локаль или такая, или такая.....)
  scope '(:locale)', locale: /#{I18n.available_locales.join("|")}/ do
    devise_for :users, skip: :omniauth_callbacks

    authenticate :user do
      mount Resque::Server.new, at: '/jobs'
    end

    root 'events#index'

    resources :events do
      # вложенный ресурс комментовX
      resources :comments, only: %i[create destroy]
      resources :photos, only: %i[create destroy]
      resources :subscriptions, only: %i[create destroy]

      post :show, on: :member
    end

    resources :users, only: %i[show edit update]
  end
end

# Если у события есть пин-код, то при обращении к "events#show" в запросе будет
# рендериться форма ввода пинкода. В эту форму юзер вводит пинкод, нажимает отправить
# и при отправке эта же форма будет выдавать post-запрос по адресу этого же события,
# а именнно "events#show" (это GET-зпрос). Добавляем двойной функционал приема POST-
# запроса по этому же url.

app/models/photo.rb
# frozen_string_literal: true

class Photo < ApplicationRecord
  belongs_to :event
  belongs_to :user

  validates :photo, presence: true
  mount_uploader :photo, PhotoUploader

  scope :persisted, -> { where.not(id: nil) }
end

app/controllers/photos_controller.rb
# frozen_string_literal: true

class PhotosController < ApplicationController
  before_action :authenticate_user!, only: :create

  before_action :set_event, only: %i[create destroy]

  before_action :set_photo, only: :destroy

  def create
    @new_photo = @event.photos.build(photo_params)
    # Проставляем у фотографии пользователя
    @new_photo.user = current_user

    if @new_photo.save
      EventEmailNotificationJob.set(wait: 5.seconds).perform_later(@new_photo) unless @event.notifications == false

      redirect_to @event, notice: t('controllers.photos.created')
    else
      render 'events/show', alert: t('controllers.photos.error')
    end
  end

  def destroy
    message = { notice: t('controllers.photos.destroyed') }

    if current_user_can_edit?(@photo)
      @photo.destroy
    else
      message = { alert: t('controllers.photos.error') }
    end

    redirect_to @event, message
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
  end

  def set_photo
    @photo = @event.photos.find(params[:id])
  end

  def photo_params
    params.fetch(:photo, {}).permit(:photo)
  end
end

app/helpers/photo_helper.rb
# frozen_string_literal: true

module PhotoHelper
  # Если у пользователя есть собственный аватар, то показываем его,
  # иначе — стандартную иконку.
  def user_avatar(user)
    user&.avatar&.url || asset_path('user.png')
  end

  # метод, который выводит миниатюрную версию аватарки:
  def user_avatar_thumb(user)
    if user&.avatar&.file.present?

      user.avatar.thumb.url
      image_tag(user.avatar.thumb.url, class: 'img-icon', title: user.name)
    else
      image_tag(asset_path('user.png'), size: '100x100', title: user.name)
    end
  end

  # Возвращает адрес рандомной фотки события, если есть хотя бы одна
  # Или ссылку на картинку по умолчанию
  def event_photo(event)
    photos = event.photos.persisted

    if photos.any?
      photos.sample.photo.url
    else
      asset_path('bg.jpg')
    end
  end

  def oauth_logo(provider)
    asset_path("#{provider}.png")
  end

  # Возвращает миниатюрную версию фотки
  def event_thumb(event)
    photos = event.photos.persisted

    if photos.any?
      photos.sample.photo.thumb.url
    else
      asset_path('event_thumb.jpg')
    end
  end
end

app/views/photos/_collection.html.erb
<div class="carousel-item <%= 'active' if photo_iteration.first? %>" style="height: 500px;" data-bs-interval="6500">
  <a href="<%= event_path(photo.event) %>">
    <%= content_tag 'div', '', class: 'banner-background',
        style: "background-image: url(#{photo.photo.url})" %>
    <div class="carousel-caption d-none d-md-block pb-0">
      <h2 class="fs-1 fw-light mb-4 btn btn-warning py-0"><%= photo.event.title %></h2>
      <p class="fw-light fs-4"><%= l(photo.event.datetime, format: :short) %><p>
    </div>
  </a>
</div>

app/views/photos/_form.html.erb
<%= form_for [@event, photo], html: { multipart: true } do |f| %>
  <%= render partial: 'partials/form_errors', locals: {model: photo} %>

  <div class="mb-3 d-flex justify-content-center border-bottom pb-3">
    <%= f.label :photo, t('photos.photo.choose_file'), class: 'btn btn-lg btn-secondary active' %>
    <%= f.file_field :photo, class: 'visually-hidden' %>
  </div>
    <a> </a>
  <div class="actions d-flex justify-content-end">
    <%= f.submit t('photos.photo.download'), class: 'btn btn-success', data: {'bs-dismiss' => 'modal'} %>
  </div>
<% end %>

app/views/photos/_photo.html.erb
<% image_title = "#{t('.add')} #{render partial: 'users/user', object: photo.user}" %>
<% if current_user_can_edit?(photo) %>
  <% delete_icon = link_to(fa_icon(class: 'trash', color: 'Tomato'), event_photo_path(photo.event, photo), method: :delete, data: {confirm: t('.are_you_sure')}) %>
  <% image_title << delete_icon %>
<% end %>

<div class="carousel-item <%= 'active' if photo_iteration.first? %>">
  <%= link_to image_tag(photo.photo.url, class: 'd-block w-100', style: 'object-fit: cover;', height: '300px'), photo.photo.url, data: {lightbox: 'roadtrip', title: image_title, alt: 'photo'} %>
</div>